version: "3.3"

services:
  bot:
    build:
      context: ../bot
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "matrix-notifer-bot"
    env_file:
    - .env
    volumes:
      - ./data:/data

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "matrix-notifer-server"
    ports:
    - "5505:5505"
    env_file:
    - .env
    volumes:
      - ./data:/data
