version: "3.3"

services:
  bot:
    image: nlion/matrix-notifier-bot:latest
    restart: unless-stopped
    container_name: "matrix-notifer-bot"
    env_file:
    - .env
    volumes:
      - ./data:/data

  server:
    image: nlion/matrix-notifier-server:latest
    restart: unless-stopped
    container_name: "matrix-notifer-server"
    ports:
    - "5505:5505"
    env_file:
    - .env
    volumes:
      - ./data:/data
