version: "3.3"

services:
  bot:
    container_name: "matrix-notifier-bot"
    image: nlion/matrix-notifier-bot:latest
    depends_on:
      - server
    env_file:
    - .env
    volumes:
      - ./data:/data
    restart: unless-stopped

  server:
    container_name: "matrix-notifier-server"
    image: nlion/matrix-notifier-server:latest
    ports:
    - "5505:5505"
    env_file:
    - .env
    volumes:
      - ./data:/data
    restart: unless-stopped
