version: "3.3"

services:
  server:
    container_name: "matrix-notifier-server"
    build:
      context: ../server
      dockerfile: Dockerfile-tests
    ports:
    - "5505:5505"
    env_file:
    - .test-env
    volumes:
      - ./data:/data
    restart: no

  bot:
    container_name: "matrix-notifier-bot"
    build:
      context: ../bot
      dockerfile: Dockerfile-tests
    depends_on:
      - server
    env_file:
    - .test-env
    volumes:
      - ./data:/data
    restart: no

  tester:
    container_name: "matrix-notifier-tester"
    build:
      context: ../tests
      dockerfile: Dockerfile
    depends_on:
      - server
      - bot
    env_file:
    - .test-env
    volumes:
      - ./data:/data
    restart: no
