name: Testing

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Start_and_Test:
    name: Start and Test

    runs-on: ubuntu-latest

    steps:
      - name: Check out code from Github
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "${{ secrets.ENVFILE }}" > .test-env

      - name: Run Matrix-Notifier
        working-directory: ./docker
        run: docker-compose -f test-docker-compose.yml --env-file .test-env up --abort-on-container-exit --exit-code-from server

      - name: Install requirements.txt
        run: pip3 install --no-cache-dir -r ./tests/requirements.txt

      - name: Run pytest
        run: pytest tests/